version: "3.9"
services:
  traefik:
    image: traefik:2.5
    ports:
      - 80:80
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)
        - traefik.http.routers.dashboard.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=80
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=api_net
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - api_net
  portainer:
    image: portainer/portainer-ce:2.11.0-alpine
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
        - traefik.http.routers.portainer.entrypoints=web
        - traefik.http.services.portainer.loadbalancer.server.port=9000
    depends_on:
      - traefik
    networks:
      - api_net
  adonis-activities:
    image: api/adonis-image
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.adonis-activities.rule=Host(`localhost`) && PathPrefix(`/api`)
        - traefik.http.routers.adonis-activities.middlewares=adonis-activities-stripprefix
        - traefik.http.middlewares.adonis-activities-stripprefix.stripprefix.prefixes=/api
        - traefik.http.routers.adonis-activities.entrypoints=web
        - traefik.http.services.adonis-activities.loadbalancer.server.port=3333
    depends_on:
      - traefik
    networks:
      - api_net
  apache-php:
    image: api/apache-php-image
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.apache-php.rule=Host(`localhost`)
        - traefik.http.routers.apache-php.entrypoints=web
        - traefik.http.services.apache-php.loadbalancer.sticky.cookie=true
        - traefik.http.services.apache-php.loadbalancer.sticky.cookie.name=sticky-cookie
        - traefik.http.services.apache-php.loadbalancer.server.port=80
    depends_on:
      - traefik
      - adonis-activities
    networks:
      - api_net
volumes:
  portainer_data:
networks:
  api_net: