version: "3.9"
services:
  traefik:
    container_name: traefik
    image: traefik:2.5
    restart: always
    ports:
      - 80:80
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=api_net
      - --entrypoints.web.address=:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)
      - traefik.http.routers.dashboard.service=api@internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - api_net
  portainer:
    image: portainer/portainer-ce:2.11.0-alpine
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    depends_on:
      - traefik
    networks:
      - api_net
  adonis-activities:
    image: api/adonis-image
    labels:
      - traefik.enable=true
      - traefik.http.routers.adonis-activities.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.routers.adonis-activities.middlewares=adonis-activities-stripprefix
      - traefik.http.middlewares.adonis-activities-stripprefix.stripprefix.prefixes=/api
      - traefik.http.routers.adonis-activities.entrypoints=web
      - traefik.http.services.adonis-activities.loadbalancer.healthcheck.path=/health
      - traefik.http.services.adonis-activities.loadbalancer.healthcheck.interval=10s
      - traefik.http.services.adonis-activities.loadbalancer.healthcheck.timeout=10s
    depends_on:
      - traefik
    networks:
      - api_net
  apache-php:
    image: api/apache-php-image
    labels:
      - traefik.enable=true
      - traefik.http.routers.apache-php.rule=Host(`localhost`)
      - traefik.http.routers.apache-php.entrypoints=web
      - traefik.http.services.apache-php.loadbalancer.sticky.cookie=true
    depends_on:
      - traefik
      - adonis-activities
    networks:
      - api_net
volumes:
  portainer_data:
networks:
  api_net: